### ISSUE TITLE
timedatectl problem on HPC?

### ISSUE THREAD

**Issue by bbolker** [eddelbuettel/anytime#113]
Just curious if anyone has seen/reported this before.  Running on the head node of an HPC system (`sessionInfo()` below).  When I try to load the package (`library(anytime)`) I get:

```
Failed to query server: Input/output error
Warning message:
In system("timedatectl", intern = TRUE) :
  running command 'timedatectl' had status 1
```

This seems to come from `Sys.timezone()` in `.onLoad`, I'll see if I can figure out some more ... aaand, it looks like `timedatectl` might not available on this system ... I'll talk to admins, but do you have any thoughts/suggestions for a workaround? (I don't need the package that badly in this application, I could strip it out ...)

---
```
R version 4.0.0 (2020-04-24)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/imkl/2019.3.199/compilers_and_libraries_2019.3.199/linux/mkl/lib/intel64_lin/libmkl_gf_lp64.so
```

**Comment by bbolker** [comment]
Never mind, this appears to be a message and not an error ...

**Comment by eddelbuettel** [comment]
So many workarounds, in fact, that we wrote a package to "work" some more "around": [`gettz`](http://cloud.r-project.org/package=gettz)

The issue was / is that 
1. TZ is not always set
2. Some distro set a link, _where_ that is varies
3. R itself had (!!) a poor heuristic
and since then R improved along the lines of `gettz`. 

So without having looked at the code now, you should _also_ get by with an explicit TZ setting.
