### ISSUE TITLE
Feature requests: more flexibly find date substring in a non-date string; and process additional incomplete date substrings

### ISSUE THREAD

**Issue by chrisumphlett** [eddelbuettel/anytime#118]
I have a list of file paths with webinar data. I'm mapping over all of those and building a single data frame. The file paths also have encoded in them some metadata, such as the product, webinar type, and the date. The date is not stored consistently however. After I've extracted the filename, which almost always has some form of date in it, I'd like to be able to do `anytime::anytime(filename)` and usually return a datetime.  [And, the corresponding `anydate` for dates].

Perhaps a workflow like this would be better:
```
datetime_substring <- anytime::find_datetime(filename)
datetime <- anytime::anytime(datetime_substring)
```

Here's an example. This shows 3 forms of dates, only one works to parse out the date when I use `anytime::anydate(webinar_name)`. 

![image](https://user-images.githubusercontent.com/7210482/97462968-a4832d80-1915-11eb-8224-8a3a0bbd28a1.png)

I learned a few things. First, that anytime is looking for the date substring only at the beginning of the string:

> anytime::anydate("asfdsfsdf 2020-01-01")
[1] NA
> anytime::anydate("2020-01-01")
[1] "2020-01-01"

This is where the workflow above would come in, to make a first pass at the first string and find the date substring.

Second, that it cannot convert sub-strings that only have partial info like this:

> anytime::anydate("May 2020")
[1] NA
> anytime::anydate("May 20, 2020")
[1] "2020-05-20"

I would like the first one to return 2020-05-01.

Third, that for some substrings where it will process a partial date, it doesn't work in the presence of additional text in the string:

> anytime::anydate("08-25")
[1] "1400-08-25"
> anytime::anydate("08-25 abcdef")
[1] NA

I am okay with the year 1400 - I can come back through and convert anything with a year prior to 2019 to current year.

**Comment by eddelbuettel** [comment]
It's tricky.  I think the 'leading stuff' maybe be best handled by an added 'filter' you could add:

```r
R> anydate(gsub("(^[a-z ]*)", "", "asfdsfsdf 2020-01-01"))
[1] "2020-01-01"
R>
```

The second one is a no-no as our parsers aim to create proper _date_ or _datetime_ objects.  And a pair on month and year is simply not a date.  So there too you may have to build something on top of what we offer.

**Comment by chrisumphlett** [comment]
Thanks. The regex is a simple workaround for that one scenario. It doesn't help in two sub-cases I have:

1. Leading numbers in the string before the date
2. Date sub-strings with a format like "May 20, 2020".

As far as the need for proper objects, admittedly I'm far from an expert on how the parsers work. My suggestion is not that you only have a month and year, but that you have a simple set of rules to impute missing parameters (day =1, month/year = current  month/year).

**Comment by eddelbuettel** [comment]
The package makes no claim to help with _any_ possible date formats.  Some remain too irregular.  There is no way around this.

It does offer you ways to accomodate the need for special treatment, see `help(addFormats)`.

I still think we should close this.

**Comment by chrisumphlett** [comment]
thanks

**Comment by eddelbuettel** [comment]
BTW your last example already works:

```r
R> anytime::anydate("May 20, 2020")
[1] "2020-05-20"
R> 
```

**Comment by chrisumphlett** [comment]
That one works, with no leading text. This doesn't work:

anydate(gsub("(^[a-z ]*)", "", "asfdsfsdf May 20, 2020"))

**Comment by eddelbuettel** [comment]
Regular expressions are very powerful.  It pays off to read up a little.  Here `[a-z]` means letters;  use `[a-z0-9]` and you may need to add punctuation etc -- this is no longer an anytime issue.  

Best of luck, and I hope you continue to find anytime useful, even with challenging data.

**Comment by chrisumphlett** [comment]
`addFormats` is promising for me. Thank you for sharing that. Is the addition of a format permanent, just for the session, something else?

> anytime::anydate("May 2020")
[1] NA
> anytime::addFormats("%b %Y")
> anytime::anydate("May 2020")
[1] "2020-05-01"

**Comment by eddelbuettel** [comment]
Just for the session.  But nothing is stopping you from adding `library(anytime); addFormats(c("....". "..."))` to your R startup.  Or maybe to the scripts or functions you use for this project.

**Comment by chrisumphlett** [comment]
Same logic also for date times. `anytime` doesn't like HH:MM with no :SS. `getFormats` always has %H:%M:%S. And then `anytime` also doesn't like am/pm either...? I don't see that in any of the formats. I'm opening a separate thread about time zones.

**Comment by chrisumphlett** [comment]
> Just for the session. But nothing is stopping you from adding `library(anytime); addFormats(c("....". "..."))` to your R startup. Or maybe to the scripts or functions you use for this project.

Yep understood, just making sure I knew if it was necessary. I'd probably to it on a project/process-level. I use `anytime` in almost every project and I've never needed to alter the formats.

**Comment by roaldarbol** [comment]
Sorry to cold-post here. I've been using *anytime* for a while now, and really love the simplicity. I often come across this exact issue (having to extract a date/datetime from a string), and I've started to keep a list of regex'es to pull out dates in a function. 

Would you consider a PR with such a function? I'll host it elsewhere otherwise, just thought it actually seemed a really neat fit to this package. :-) 

I can also have a look at how you coded `addFormats`, and I could possibly allow users to add their own regex expression too.

**Comment by eddelbuettel** [comment]
It all depends. Look at old issues: sometimes proposed date formats were unambigious enough that adding them made sense.  But some might have opened the door misinterpretation:  month followed by day or day followed by month?  We cannot do it randomly.

That's why we give you an open door with `addFormats`:  _you_ can add what _you_ need it `anytime` needs rounding out.  Adding a whole regexp-munging layer may however be a step too far.

**Comment by roaldarbol** [comment]
Ah fair enough. Just to be clear; I was envisioning a function that can parse out *some* types of dates from strings. So a function that can take the formats that are in `getFormats` and use them in a `str_extract`-like way. 
So in case a user has an additional format, they can add it to the formats with `addFormat` and then the `str_extract`-like function can make use of that too.

So an example:
```r
string <- "A long string where this date, 20-10-2020, is hiding"
datetime <- find_datetime(string)
[1] "20-10-2020"

# In case the format is not supported
addFormat("%d %b %y") # Add new format
datetime <- find_datetime(unsupported_string)
```

Anyway, I'll play around with it - I can make a PR, but with no pressure to accept it, as I said, I'll just place the code elsewhere otherwise. :-)

**Comment by eddelbuettel** [comment]
It's an interesting idea but it does stray a little from the original mission of the package.  It's not called 'anytimeanywhere' for a reason :wink:

That said, there may be way.  But as I recall, the underlying date-time parser from Boost wants the narrower expression we give it rather than more general regular expression.  Plus, regular expression support often requires _linking_ making build and deployment a wee bit more complicated.  And then there is of course the joy of regular expressions.  How would you treat a string with more than one date?  "It was bitterly cold during the period from 2024-12-10 to 2024-12-12."  Return one?  Return both?  And what if the second date is partial? "It was bitterly cold during the period from 2024-12-10 to 12.".  Cans and cans of worms.

**Comment by roaldarbol** [comment]
Haha, IO see where you're getting at. 

> How would you treat a string with more than one date? "It was bitterly cold during the period from 2024-12-10 to 2024-12-12." Return one? Return both?

Here I'd definitely return two dates, maybe set a parameter to choose which ones should be returned.

>  And what if the second date is partial? "It was bitterly cold during the period from 2024-12-10 to 12.". Cans and cans of worms.

TBH I'd argue it's also fair to simply look for the actual date. Sure there might be some who'd want to get *that* done, but I think that's a quite reasonable place to draw the line. :-)

I'll maybe just make a new package that does this instead; I can give a heads up if/when I get it done. ;-)
