### ISSUE TITLE
European vs US date formats

### ISSUE THREAD

**Issue by chrisumphlett** [eddelbuettel/anytime#119]
I have a list of datetimes that are a mixture of European (DD/MM/YYYY) and US formats (MM/DD/YYYY). The timezone value is included. `anytime` successfully parses these dates in a way that seems to ignore the timezone-- it reads as MM/DD/YYYY regardless. If it's a European date with a day higher than 12 then it returns `NA` (eg, `15/01/2020 09:40 AM CET`).

These are all string values. The Timezone is a string, not part of the object-- so I think this line from the README does not apply: *Further, as the `Boost Date_Time` library cannot resolve timezones on the Windows platform...*

I can add the European format and pickup the example that led to NA above:
> anytime::addFormats("%d/%m/%Y %H:%M:%S %p %Z")
> anytime::anytime("15/01/2020 09:40:00 AM CET")
[1] "2020-01-15 09:40:00 EST"

But, if I need to use Euro format for a day earlier than 12 it's wrong (reverts to US parsing):
> anytime::anytime("1/12/2020 09:40:00 AM CET")
[1] "2020-01-12 09:40:00 EST"

This should be "2020-12-01 09:40:00". 

This is arguably a date parsing error, rather than an issue with incomplete date or extra text hence why I opened a separate issue.

**Comment by eddelbuettel** [comment]
Please see old issue tickets. This is a duplicate.

**Comment by eddelbuettel** [comment]
https://github.com/eddelbuettel/anytime/blob/7481e69a096cab7cfccd98d92038de1b067a7d64/vignettes/rmd/anytime-intro.Rmd#L289-L301

**Comment by eddelbuettel** [comment]
Also, you format string is plain wrong. %H is for 24 hour clocks.  You may have meant %I.   But I wouldn't rely on 12h times with am and pm.  Use ISO formats with 24 hours if at all possible.

Lastly, you appear to have some hope that the parsing has some metaphysical knowledge of whether

    02/03

is March 2nd or February 3rd.  It doesn't.  First match wins, which is why the encoded preference for US formats along with slashes or hyphes is noted.  _If you add a European format it will be tried first and matches._   That is a feature, not a bug.
