### ISSUE TITLE
Inconsistent handling of vectors with unknown values  

### ISSUE THREAD

**Issue by nikolkj** [eddelbuettel/anytime#126]
Noticed that `anytime::anydate()` has inconsistent output if there are NA values present in the input vector. 

It looks like related to data-type handling. Character vectors are decoded fine, but numeric vectors return unexpected results. There also appears to be some impact based on where the NA values are located in vector. 

For example:
```
> vec1 = c(NA, "20140213", "20150417", NA)
 vec2 = as.numeric(vec1)
```

```
> anytime::anydate(vec1)
[ 1] NA           "2014-02-13" "2015-04-17" NA     
```

```
> anytime::anydate(vec2)
 [1] NA           **"1970-08-21" "1970-08-22"** NA 
```

Conversely, if the leading NA value is removed, then both vectors are decoded without issue:
```
> vec1 = c("20140213", "20150417", NA)
> vec2 = as.numeric(vec1)
```

```
> anytime::anydate(vec1)
[1] "2014-02-13" "2015-04-17" NA   
``` 

```
> anytime::anydate(vec2)
[1] "2014-02-13" "2015-04-17" NA
```

environment details:
> version.string R version 4.2.0 (2022-04-22 ucrt)
> anytime v0.3.9

> Edition	Windows 10 Enterprise
> Version	20H2
> Installed on	‎8/‎17/‎2021
> OS build	19042.1706
> Experience	Windows Feature Experience Pack 120.2212.4170.0
> Processor	Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz   2.11 GHz

**Comment by eddelbuettel** [comment]
That's an R thing I can do nothing about.  A _vector_ is forced / required / defined to be of one type, and (AFAIK) the first value determines the type for the whole vector.  `anytime()` and `anydate()` then receive that vector (as a whole) and do operations _given_ the representation type of the vector.  

I am fairly sure we discussed this here before so you may additional information if you search among the closed issues.

The other issue is that _initially_ we took a `numeric` (as in your `vec2`) to be a 'transcribed' character (as here) and reconverted to char.  Turns out that is a bad idea because we really need to be like R itself and treat `5` (or `5L`) as the offset to the epoch so that `anydate(5)` gets us Jan 6, 1970.  But because honour old behaviour and APIs we added an option `oldHeuristic` -- but apparently only for `anytime`:

```r
> anytime(20120213, oldHeuristic=TRUE)      
 [1] "2012-02-13 CST"                                      
 > 
```

If you want to port that to `anydate` or shimmy something else in please follow up with a proposal.  Otherwise I think we can close this.  If you disagree, or have other material, please feel free to reopen.  Thanks of trying `anytime` !

PS This works: 

```r
> anydate(anytime(20120213, oldHeuristic=TRUE))   
 [1] "2012-02-13"                                                          
 >  
 ```

PPS  I was not quite correct on `oldHeuristic`. It is related to `char <-> numeric` but the values you have here don't fly, we get bad values.  The overall issue remains: you may need to take care of leading `NA` values.
