### ISSUE TITLE
Trivial conversion to NA

### ISSUE THREAD

**Issue by DavideMagno** [eddelbuettel/anytime#127]
Hi, I am a big fan of the package, but how is it possible that a trivial conversion like the following returns NA?
`anytime::anydate("26/10/2022")`
It can only be %d/%m/%Y, how can the package not recognize it?

**Comment by eddelbuettel** [comment]
Because day-month and month-day are ambigious, "guessing is risky" and so we use the cultural norms of delimiter to choose between day-month and month-day.  That has served us well for the six plus years the package has been out. 

For some formats we cannot help you and you need a format string.  This may be one of those examples.  You can see the full list at `anytime::getFormats()`. So I think we can close this. (And remember you can add a format string "for the session" to anytime, it will go to the front of the list and matched before alternatives. )


Thanks for being a fan and user though :smile:
