### ISSUE TITLE
Allow format strings to be added

### ISSUE THREAD

**Issue by eddelbuettel** [eddelbuettel/anytime#3]
Would allow to overcome the currently fixed set for _odd_ formats like
- `%y` for two-digit year, or even 
- `%I %p` for 12 hour time and am/pm,
- any other format we don't currently have.

**Comment by adisarid** [comment]
Great initiative for doing this package. Important feature in format strings context: some languages/localization (e.g., Hebrew) specify date in `%d/%m/%Y` instead of the worldwide standard `(%m/%d/%Y)`. When inputting a vector such as:
`anytime(c("14/09/2016", "01/09/2016"))`
You get an NA for the first value and an opposite day-month for the second value, though you can probably deduce the meaning from some values (in the example the first value) and apply it on "localization-ambiguous" values (in the example, the second).
Probably a unique situation (according to localization), so should be applied using a parameter.

**Comment by eddelbuettel** [comment]
Same with many European formats which do, say, `%d.%m.%Y`.

But this (famously) clashes with what North America does in its (braindead, but prevalent) `%m/%d/%Y` -- modulo the separators.  There is no way to deal with the safely -- hence everybody's preference for ISO formats -- and `strptime()` et al have the same issue.  I am not sure localization can help.

You can pre-load formats in the next version:

``` r
R> anytime:::addFormat("%d.%m.%Y") # Europe
R> anytime("10.11.2012")
[1] "2012-11-10 CST"
R> 
```

If you can work out how localization could help _at the C++ level offered by Boost_ I'd be interested.  Otherwise it is the "same old" issue also plagueing `strptime()` et al, and there is little I can do.

**Comment by eddelbuettel** [comment]
Good news:  Boost has `%x` for locale-dependent input, [see the docs](http://www.boost.org/doc/libs/1_61_0/doc/html/date_time/date_time_io.html#date_time.format_flags).

I plan to test that.

**Comment by eddelbuettel** [comment]
Format strings can now be added.

**Comment by adisarid** [comment]
Awesome, thanks!
