### ISSUE TITLE
Integer seconds from Epoch fails, numeric version works.

### ISSUE THREAD

**Issue by rodonn** [eddelbuettel/anytime#56]
```
library(anytime)
anytime(1483228800L)
[1] NA
anytime(1*1483228800L)
[1] "2016-12-31 16:00:00 PST"
```

Multiplying by 1 to convert to a numeric seems to fix the problem.

**Comment by eddelbuettel** [comment]
I just explained that [on StackOverflow too](http://stackoverflow.com/questions/42316895/why-does-anytime-return-na-in-some-cases).  I don't consider it to be a bug as 

- `1483228800L` is not really a common, useful, semi-standard format for humans
- `POSIXct` is a numeric type which is why it works for numerics
- integer input gets converted to string to that we can parse something actually useful like 20170216L

If this is very important to you, maybe you can work out a patch.  To me it is a case of bad input.

**Comment by eddelbuettel** [comment]
Ok, despite my own best intentions I just put something in:

```r
R> library(anytime)
R> anytime(20170226)
[1] "2017-02-26 CST"
R> anytime(20170226L)
[1] "2017-02-26 CST"
R> anytime(1483228800L)           # this now works
[1] "2016-12-31 18:00:00 CST"
R> 
```

Let me test it some more.
