### ISSUE TITLE
anytime(numeric) kills R session

### ISSUE THREAD

**Issue by zx8754** [eddelbuettel/anytime#60]
Running below kills R session (RStudio Version 1.0.136.)

```R
library(anytime) #anytime_0.2.1

anytime(41275)
```

Didn't test it on dev version, could be a duplicate of issue: #56 

**sessionInfo**

```R
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] anytime_0.2.1

loaded via a namespace (and not attached):
[1] tools_3.3.2  Rcpp_0.12.10
```

**Comment by zx8754** [comment]
Just for info I typed `anytime` instead of `anydate`, and killed my session.

My intention was below which still doesn't work. Maybe it is too much to ask but I was expecting below output when used with `anydate`:

```R
# current output
anydate(41275)
# [1] "4127-01-01"

# expected output
as.Date(41275, origin = "1899-12-30")
# [1] "2013-01-01"
```

**Comment by eddelbuettel** [comment]
Two things here:

1)  Different origins are not supported.  That is opposite to the philosophy of `anytime()` / `anydate()`. If you need that, use `as.Date()` as you did.  Converting from `integer` is already stretching it as the core goal really was parsing from text for variants of yyyymmdd.

2) The crash is likely a known (and *fixed*) RStudio issue in them also using Boost, but older versions, and in a non-shielded namespace.  The good news is that this *is* fixed in newer version--take a [daily RStudio build](https://dailies.rstudio.com/) of version 1.1.129 or higher.

```r
R> library(anytime)
R> anytime(41275)
[1] "2083-01-03"
R> anydate(41275)
[1] "2083-01-03"
R> RStudio.Version()$version
[1] ‘1.1.135’
R> 
```
