### ISSUE TITLE
anytime cannot handle PM or AM if it occures at the end

### ISSUE THREAD

**Issue by arrabi** [eddelbuettel/anytime#82]
```r
> anytime("10/20/2018 08:26:46 PM")
[1] "2018-10-20 PDT"
```

as you can see, the time is omitted because PM was added. If I remove the PM, it's included:

```r
> anytime("10/20/2018 08:26:46")
[1] "2018-10-20 08:26:46 PDT" 
```

**Comment by eddelbuettel** [comment]
I'd be careful -- PM/AM are used with twelve hour formats for which (IIRC) %I instead of %H is used.

`anytime()` allows you to add user-specified formats to the known set so you can accomodate this if you want to.   To me this does not seem like a bug or something actionable from my side.   Shall we close this?

**Comment by eddelbuettel** [comment]
And the other issue worth reminding oneself of is ... that Boost Date_Time does not allow AM/PM to be parse on input:  https://www.boost.org/doc/libs/1_68_0/doc/html/date_time/date_time_io.html

The table has the `!` flag for "not usable for input (at this time)." and it is right at the `%p` flag.

We have the `useR=TRUE` to revert back to the R parser who can handle this.  Sorry, but anytime can't do more for you here.
